artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: "wikitext-2-raw-v1" #***"sample-10BT"
  dataset: "wikitext" #***"HuggingFaceFW/fineweb-edu"
  local_data_file: artifacts/data_ingestion/data

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_name: "wikitext-2-raw-v1" #***"sample-10BT"
  dataset: "wikitext" #***"HuggingFaceFW/fineweb-edu"
  downloaded_files: artifacts/data_ingestion/data
  local_data_file: artifacts/data_transformation/data
  shard_size: 1000000 #*** 100000000 small shard size for toy "wikitext" dataset

gpt_config:
  root_dir: artifacts/model_config
  verification_info_dir: artifacts/model_config/verification_info
  verification_summary_file: verification_model_summary.txt
  verification_weights_file: verification_initial_weights.pt
  src_seq_len: 50
  tgt_seq_len: 50
  d_model: 512
  N: 6
  h: 8
  dropout: 0.1
  d_ff: 2048

model_training:
  root_dir: artifacts/model_training
  model_folder: artifacts/model_training/model_en_fa_weights
  model_basename: "tmodel_"
  tensorboard_log_dir: logs
  lr: 0.0001
  max_len: 50
  preload:
  num_epochs: 1 

model_evaluation:
  root_dir: artifacts/model_evaluation

model_inference:
root_dir: artifacts/model_inference


